---
- name: Add a new AllowUser
  hosts: bor
  vars:
    new_user_name: rafael
  tasks:
    - command: grep "^AllowGroups " /etc/ssh/sshd_config
      register: old_user_list
    - lineinfile:
        regexp: "^AllowGroups .+"
        line: "{{ old_user_list.stdout }} {{new_user_name}}"
        when: old_user_list.rc == 0
