---
- name: Add users to host
  hosts: all
  vars_files:
    - vars/users.yml
  tasks:
    - name: Add user
      user:
        name: "{{ user_name }}"
        state: "{{ user_state }}"
        shell: /bin/bash
        groups: sudo
        append: yes
