---
- name: Add a new AllowUser
  hosts: bor
  vars:
    new-user-name: rafael
  tasks:
    - command: grep "^AllowUsers " /etc/ssh/sshd_config
      register: old_user_list
    - lineinfile:
      regexp: "^AllowUsers .+"
      line: "{{ old_user_list.stdout }} {{new-user-name}}"
    when: old_user_list.rc == 0
